name: Publish to PyPI

on:
  release:
    types: [created]
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install bumpversion
      
      - name: Bump version if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Bump version according to input
          bumpversion ${{ github.event.inputs.version_bump }}
          
          # Push the commit and tag
          git push
          git push --tags
      
      - name: Build package
        run: |
          python -m build
      
      - name: Check distribution
        run: |
          python -m twine check dist/*
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # Uncomment for TestPyPI
          # repository_url: https://test.pypi.org/legacy/