# Site information
site_name: Cascadeâš¡ð“‚§Ï†âˆž Symbiotic Computing Platform
site_description: A revolutionary computing paradigm with consciousness field dynamics and phi-harmonic processing
site_author: Quantum Collaborative Team
site_url: https://github.com/gwelby/quantum_collaborative

# Repository information
repo_name: gwelby/quantum_collaborative
repo_url: https://github.com/gwelby/quantum_collaborative
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Quantum Collaborative Team

# Configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: CASCADE_QUICKSTART.md
      - Installation: INSTALLATION.md
      - Tutorials: CASCADE_TUTORIAL.md
      - Documentation: CASCADE_DOCUMENTATION.md
  - Guides:
      - Creating Demo Videos: creating_demo_videos.md
      - Demo Video Script: demo_video_script.md
      - OBS Setup Guide: guides/obs_setup_guide.md
      - Lenovo P1 Installation: guides/lenovo_p1_installation.md
      - Network Visualization: network_visualization.md
  - Publishing & Development:
      - PyPI Publishing: guides/pypi_publishing_guide.md
      - GitHub Pages Setup: guides/github_pages_setup.md
      - Community Building: community_plan.md
  - Architecture:
      - System Architecture: system_architecture.md
      - API Reference: api/index.md
  - Community:
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Project Status: PROJECT_STATUS.md
      - Changelog: CHANGELOG.md